### ISSUE TITLE
dependency creep into production

### ISSUE THREAD

**Issue by oranoran** [thiagobustamante/typescript-rest-swagger#107]
When using decorators exported by typescript-rest-swagger, a package.json file would have to declare typescript-rest-swagger as a "regular" non-dev dependency, otherwise code using the decorators would fail to compile.
In turn, typescript-rest-swagger has non-dev dependencies on typescript, typescript-rest and other packages.

As a result, any project using typescript-rest-swagger with decorators inherits production dependencies on typescript. Such dependency creep is bad for operations (much larger images) and for security (larger surface of attack).

For example, in my current project, the size of the node_modules directory after `yarn install --production` jumped by 65MB and 76 additional modules!

Would it be possible to just declare all these dependencies in typescript-rest-swagger as devDependencies? This will not affect how the CLI is used by developers, but will trim things down for production. Any reason not to?

Otherwise - a fix to this would probably require splitting the decorators (and any other exports that need to be imported from the user's code) into a separate NPM package, which is a robust solution but is a bit more complex.

**Comment by oranoran** [comment]
Added suggested fix with PR #108 - just moved the dependencies and everything seems to work just fine after.

**Comment by thiagobustamante** [comment]
Hi @oranoran ,

Thanks for this PR. makes a lot o sense. Already merged
