### ISSUE TITLE
@Example<string>('mystring') results in empty example

### ISSUE THREAD

**Issue by creadicted** [thiagobustamante/typescript-rest-swagger#13]
I mistaken the correct purpose of the @Example decorator. 
Please forget my question. I thought it can be used for the request parameters instead of the result.

---
If I have a request
```
@GET
@Path('/:uuid')
public async myRequest(@PathParam('uuid') uuid: string): Promise<any> {
...
}
```
I would like to describe it with an example. For this string parameter my example would be that: 

`@Example<string>('b23d9353-761b-4fed-b517-58810d69354f')`

the result in the swagger documentation is: 
`{}`

Have I missed something? 
Best and thank you

**Comment by tnrich** [comment]
@ngraef why did you close this?
