### ISSUE TITLE
Default value for version is not set from npm package version

### ISSUE THREAD

**Issue by michaelkruglos** [thiagobustamante/typescript-rest-swagger#15]
Default value for version is not set from npm package version, despite what's written in the documentation.

https://github.com/thiagobustamante/typescript-rest-swagger/blob/82e1f8799ff6c0621407206460a3c11153557666/src/config.ts#L32

**Comment by ngraef** [comment]
Should be fixed by 88a9385ef0c244fc847accd0aac5c651978684be in `0.0.12` release.

**Comment by michaelkruglos** [comment]
Thank you so much!
