### ISSUE TITLE
Is possible use interface for model?

### ISSUE THREAD

**Issue by vellengs** [thiagobustamante/typescript-rest-swagger#16]
for example 

`
@Path('/account')

export class AccountController {
    /**
     * Get account info by name.
     * @param name The name
     */
    @Path(':name')
    @GET
    getName( @PathParam('name') name: string): IPaginate {
        return {
            page: 0,
            size: 10,
            sort: ''
        };
    }
}
`

IPaginate is a typescript interface.

**Comment by ngraef** [comment]
Yes, interfaces are supported. Please open an issue with specific details if you encounter a problem.

**Comment by vellengs** [comment]
I found the interface should be exported;
That mean not global define interface. then it works.
