### ISSUE TITLE
Body param of type string doesn't create text area on the swagger page

### ISSUE THREAD

**Issue by raghavmehta1996** [thiagobustamante/typescript-rest-swagger#17]
```ts
@Path('/current/academic_history')
@Accept('text/html')
@BodyOptions({type: 'text/html', limit: '50mb'})
@PUT
updateCurrentUserAcademicHistory(rawText: string): Promise<AcademicHistory> {
  ...
}
```

This results in the following

<img width="932" alt="screen shot 2017-09-29 at 6 19 13 pm" src="https://user-images.githubusercontent.com/12293899/31040962-dc051704-a542-11e7-9513-4260260a98ee.png">

A text box is missing on the swagger panel where a user can input the rawText.

**Comment by creadicted** [comment]
Since i changed to the version with the new layout. All my parameter input boxes are gone. So I am not sure if it has something todo with the design or if it requires a new description of parameters.

**Comment by ngraef** [comment]
@creadicted The input boxes are now hidden initially. There should be a "Try it out" button; once you click that, the input boxes appear.

@raghavmehta1996 Just pushed a fix for this.

**Comment by creadicted** [comment]
@ngraef Thank you for your response. I noticed that. But the boxes where still missing.

**Comment by ngraef** [comment]
@creadicted What kind of parameters (body, path, etc.) and what data type? Any relevant swagger yml/json snippets you can share would be helpful.
