### ISSUE TITLE
Array Examples Not Handled Properly

### ISSUE THREAD

**Issue by JohnCMcDonough** [thiagobustamante/typescript-rest-swagger#31]
When you create an example where the root object is an array, the example that it generates is an object with "0", "1", etc... set.

```
@Example<Array<RuleExecution>>([{
    id: '03c5c3f5-726d-49a8-b794-782fb34d2917',
    tenantId: '9c4c3faa-b592-448a-a307-cad105a63606',
    facts: {
        'FirstName': 'John',
        'LastName':'redacted'
    }
}])
```
This annotation gives the example: 
```
{
  "0": {
    "id": "03c5c3f5-726d-49a8-b794-782fb34d2917",
    "tenantId": "9c4c3faa-b592-448a-a307-cad105a63606",
    "facts": {
        "FirstName": "John",
        "LastName":"redacted"
    }
  }
}
```

**Comment by JohnCMcDonough** [comment]
I've found what I think to be the issue.

In `methodGenerator.ts`, you have a method that's called `getExamplesValue(argument:any)`.

In that, you assume the returned item to be an object. It can also be a string. These changes seem to have fixed it.


```
private getExamplesValue(argument: any) {
    let example: any = {};
    if (argument.properties) {
        argument.properties.forEach((p: any) => {
            example[p.name.text] = this.getInitializerValue(p.initializer);
        });
    } else {
        const obj = this.getInitializerValue(argument);
        if (Array.isArray(obj))
            return obj;
        example = _.merge(example, obj);
    }
    return example;
}
```

The added lines below seem to fix the problems, however, I'm not sure why the `_.merge` is being used with the example Object. I don't know if this fix would cause issues.
```
if (Array.isArray(obj))
            return obj;
```

**Comment by thiagobustamante** [comment]
Hi @JohnCMcDonough,

Yes you are right. The problem is that function. We don't need this _.merge call. It is causing the issue.
