### ISSUE TITLE
Response documentation for 204

### ISSUE THREAD

**Issue by mnishizawa** [thiagobustamante/typescript-rest-swagger#39]
I have an endpoint that only returns a 204 upon success.  However, when the swagger documentation is generated, it adds a 200 and I can't get rid of the model associated to the response when I use the @Response tag.

Ideally, I would be able to specify only the responses I actually produce and a 204 shouldn't expect a model.

**Comment by ngraef** [comment]
Can you share the code for the endpoint method? A 204 should be generated for methods that don't return anything (i.e. `void` return type in function signature).

**Comment by mnishizawa** [comment]
That was it.  I was returning Promise<any> and just not giving it anything.  Thanks!
