### ISSUE TITLE
Multiple API keys supported with @Security decorator ?

### ISSUE THREAD

**Issue by GreGosPhaTos** [thiagobustamante/typescript-rest-swagger#51]
Hello ! I have a quiet similiar question than here => swagger-api/swagger-codegen#5224 (comment)

And if I try to add more than one @Security() decorator at the method level I get an error "Only one Security decorator allowed in ... {method or className}".
Is there a way to add multiple apikeys in the swagger specs ?

**Comment by ngraef** [comment]
Support for multiple `@Security` decorators was added in 1dbf583, however there hasn't been a release since then. It will ship with the next release.

**Comment by GreGosPhaTos** [comment]
Ok awesome ! 
Thanks @ngraef

**Comment by GreGosPhaTos** [comment]
@ngraef Any ideas when this feature will be released ?

**Comment by thiagobustamante** [comment]
@GreGosPhaTos , It is published. Version 0.0.20

**Comment by GreGosPhaTos** [comment]
Thanks guys !!
