### ISSUE TITLE
Adding 'Schemes' to be auto generated

### ISSUE THREAD

**Issue by AlexCharlton93** [thiagobustamante/typescript-rest-swagger#52]
I'm trying to add the 'https' scheme but can't find anything in the documentation for this.

i.e. 
schemes:
  - https

Can anyone advise?

Thanks,
Alex

**Comment by ngraef** [comment]
Try using the `spec` property of [swaggerconfig.json](https://github.com/thiagobustamante/typescript-rest-swagger#swaggerconfigjson) to set any values that aren't explicitly supported.

```json
{
  "name": "my-api",
  "spec": {
    "schemes": ["https"]
  }
}
```
