### ISSUE TITLE
I'm an idiot, but how to fix "swaggerGen: command not found"?

### ISSUE THREAD

**Issue by scottschafer** [thiagobustamante/typescript-rest-swagger#66]
I've run:
npm install typescript-rest-swagger -g

But this doesn't seem to install "swaggerGen". I just get "swaggerGen: command not found" when I run:

swaggerGen -c ./swaggerConfig.json

How to fix this?

**Comment by scottschafer** [comment]
It's a node config thing. Never mind

**Comment by Lasitha92** [comment]
If you can mention how you fixed this, it will be helpful

**Comment by scottschafer** [comment]
@Lasitha92, I'm sorry I didn't put more details. Honestly, I don't remember at this point except that I think I was using homebrew on a Mac to install node. This resulted in some issues, which other people also run into. The issue went away after I:
1. COMPLETELY uninstalled node
2. Used 'nvm' to install node (see https://itnext.io/nvm-the-easiest-way-to-switch-node-js-environments-on-your-machine-in-a-flash-17babb7d5f1b etc)

**Comment by abdelrahmannasr** [comment]
are anyone fixes this issue?
I couldn't figure out the issue of swagggerGen command is not found

**Comment by Lasitha92** [comment]
I found that, if we install this locally instead of globally, command is working fine
