### ISSUE TITLE
-t or -p not work

### ISSUE THREAD

**Issue by kozmonotselcuk** [thiagobustamante/typescript-rest-swagger#69]
hi, first thanks for that package.

work - > swaggerGen -c ./swaggerConfig.json

not work ->
swaggerGen -c ./swaggerConfig.json -t # load {cwd}/tsconfig.json
swaggerGen -c ./swaggerConfig.json -p ./tsconfig.json # load custom tsconfig.json

-t or -p wont find

terminal output with -h
Tree-Gateway Swagger tool

Optional arguments:
  -h, --help            Show this help message and exit.
  -v, --version         Show program's version number and exit.
  -c CONFIG, --config CONFIG
                        The swagger config file (swagger.json).

i have been using v0.0.23

**Comment by thiagobustamante** [comment]
These options were introduced in 0.0.24 release. It was in the readme file before the release is published. I just publish it now.
