### ISSUE TITLE
Any request with Array<structure> in body not correctly parsed

### ISSUE THREAD

**Issue by Insalien** [thiagobustamante/typescript-rest-swagger#72]
My following code 

```typescript
@Path('test')
@POST
test(data: string[]): any {
}
```

will generate

```json
"parameters": [
	{
		"description": "",
		"in": "body",
		"name": "data",
		"required": true,
		"schema": {
			"type": "array"
		},
		"items": {
			"type": "string"
		}
	}
]
```

instead of

```json
"parameters": [
	{
		"description": "",
		"in": "body",
		"name": "data",
		"required": true,
		"schema": {
			"type": "array",
			"items": {
				"type": "string"
			}
		}
	}
]
```

**Comment by Insalien** [comment]
Please find here my patch for this issue

[typescript-rest-swagger.body.array.patch.txt](https://github.com/thiagobustamante/typescript-rest-swagger/files/3019054/typescript-rest-swagger.body.array.patch.txt)

**Comment by manusgallagher** [comment]
@Insalien could you merge this change in and generate a new package for this fix?

**Comment by manusgallagher** [comment]
I have added the change here: https://github.com/thiagobustamante/typescript-rest-swagger/pull/77
