### ISSUE TITLE
Best practice? - Use all classes in subfolder referenced in "entryFile" when generating swagger.json.

### ISSUE THREAD

**Issue by creadicted** [thiagobustamante/typescript-rest-swagger#8]
Is there a best practice if I have a similar structure to this: 

 - controllers
	 - users 
		- getAllUsers.ts
		- getUser.ts
	 - tasks
		- getAllTasks.ts
		- getTask.ts

to reference those entry points when generating swagger.json file? 

--- 
Thank you for the work and effort of this project!

**Comment by thiagobustamante** [comment]
Hi,

Thanks for your feedback!

In the configuration file, just reference the main app file. The generator will follow the imports from that file and find all the others (if all those files are referenced at least once).

**Comment by creadicted** [comment]
Thank you for your reply! 
I am currently experimenting with the boilerplate project. The only way that I could get the swagger generator to pick up the files was by directly set the path: 

`"entryFile": "./src/controllers/index.ts",`

and have every controller referenced in this index file as follows: 
`export default [FirstController, SecondController, ...];`

If i just reference the server.ts where I use:
`Server.loadServices(this.app, 'controllers/**/*.ts', __dirname);`
or 
`Server.loadServices(this.app, 'controllers/*', __dirname);`
to reference to the folder, the swagger.json file stays empty.
I am sorry if I missed something in the documentation.

**Comment by vrudikov** [comment]
@creadicted no. you are right. i get the same issue.
@thiagobustamante you can reproduce the issue in my our [demo-app branch](https://github.com/vrudikov/typescript-rest-boilerplate/tree/swagger-gen-issue)

**Comment by thiagobustamante** [comment]
Ok. Thanks @vrudikov. The problem is that typescript-rest-swagger works by analyzing the *.ts files and following the ```import``` statements. ```Server.loadServices``` use dynamic ```require```statements. So it is a real problem.

**Comment by thiagobustamante** [comment]
I don't know if we can follow those dynamic require statements... Maybe we can support multiple entry points in the configuration file...

```
"entryFile": ["./src/controllers/*.ts"]
```

What do you think?

**Comment by vrudikov** [comment]
How do you analyze when `Server.buildServices` is used? Are you searching for string `Server.buildServices` and try to get parameters from method? Or you searching for InternalServer instance and analyze it somehow? I see that you call `buildServices` in `Server.loadServices`.

So we have common part. I need to understand how you build that stuff in `typescript-rest-swagger`

**Comment by vrudikov** [comment]
@thiagobustamante ?

**Comment by thiagobustamante** [comment]
Hi, @vrudikov ,

I use the typescript parser to analyze the source files. 

```typescript
import * as ts from 'typescript';
// ...
this.program = ts.createProgram([entryFile], {});
```

The reason it works in one scenario and does not in the other is not how I make the analyze itself. I don't search for ```Server.buildServices``` or ```Server.loadServices``` calls. 

I just track the annotaded classes and methods found by the typescript parser (Take a better look [here](https://github.com/thiagobustamante/typescript-rest-swagger/blob/master/src/metadata/metadataGenerator.ts)).

The reason that makes it works for the first scenario is that the entryPoint contains ```import```statements for the rest of the code, and that allows the typescript parser to find out this other files.

You can use ```Server.loadServices``` without add any ```import``` statement in your entryFile, once it will load those files dynamically.

So, in resume, I don't make any different think that makes the ```Server.buildServices``` works. But to pass the classes to buildServices, it is needed that these classes are imported, what makes the typescript parser find them.

If you change the ```import``` statements for dynamic ```require``` statements the generator stops to work, even using ```Service.buildServices```

```typescript
const MyService = require('./myControllers').MyService;
Service.buildServices(app, Myservice);  
// Will not generate anything in the swagger file.
```

What we need to fix is turn all necessary files visible to the parser:

```typescript
this.program = ts.createProgram([entryFile], {});
```

I thing that the easiest way is to receive more ```entry files``` from the configuration file. The other solution is to try analyze the first entry file and find out other dynamic references... But it is not so trivial. 

Maybe we should receive a base folder as the source entry point.... and include all *.ts files under it. It changes a little the semantics of our ```entryFile``` in the configuration file.... But maybe it would be the best option.

**Comment by unknow** [comment]
I have the same issue. Maybe creating an `entryDir` is a good solution. And search the ` .ts` files included in sub-directories from that point.
