### ISSUE TITLE
swagger.json not picking up generated endpoints

### ISSUE THREAD

**Issue by tgreen7** [thiagobustamante/typescript-rest-swagger#89]
I have a function like:

```
export default function generateBasicEndpoints(model): any {
  @Tags(capitalize(model))
  @Path(pluralize(model))
  class GenericController {
    @GET
    @Path("/:id")
    public async getSingleItem(
      @PathParam("id") entityId: string
    ): Promise<GetSingleItemResult> {
      // some code
   }
  }

 return GenericController
}
```

which I then can call to make my endpoints. However, when i do it like this swaggerGen does not pick up the routes.

Is it not possible to generate endpoints like this and use swaggerGen? Or do i need more configuration?

**Comment by thiagobustamante** [comment]
Hi @tgreen7  ,

It is not supported... swaggerGen performs a static analysis of the code

**Comment by tnrich** [comment]
Closing this as it is currently not supported
