### ISSUE TITLE
Is there anyway to use the interface or class definition from outside module

### ISSUE THREAD

**Issue by shawnliujw** [thiagobustamante/typescript-rest-swagger#91]
for example i defined Response like 
`@Response<ResponseError>`

when `ResponseError` comes from current project, it worked fine . but if i import `ResponseError` from other outside module , then it throws error 
` No matching model found for referenced type ResponseError`

**Comment by shawnliujw** [comment]
find the solution , due to the `MetadataGenerator` ignore to load the source files from `**/node_modules/**` , then when load the type from these files , will throw error.  
the easiest way is  just remove `ignore: ['**/node_modules/**'],`  from your configuration file

**Comment by JulienSergent** [comment]
this problem is resolve in PR#86 not actually merge
